version: '3.5'
services:
  rabbitmq:
    networks:
      - ms
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    networks:
      - ms
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: nutritionist
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./docker/mongo/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
  nutritionist-service:
    build: ./
    networks:
      - ms
    ports:
      - "8082:8082"
networks:
  ms:
    name: ms