server:
  port: 8082
spring:
  data:
    mongodb:
      database: nutritionist
      username: mongo
      password: mongo
      host: localhost
      port: 27017
rabbitmq:
  host: localhost
  queue: nutritionEventsQueue

