server:
  port: 8082
spring:
  data:
    mongodb:
      database: nutritionist
      username: mongo
      password: mongo
      host: localhost
      port: 27017
rabbitmq:
  host: localhost
  queue: nutritionEventsQueue

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      user-service:
        connectTimeout: 2000
        readTimeout: 2000