server:
  port: 8082
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  data:
    mongodb:
      database: nutritionist
      username: mongo
      password: mongo
      host: localhost
      port: 27017
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      user-service:
        connectTimeout: 2000
        readTimeout: 2000
  httpclient:
    enabled: true

#custom properties
rabbitmq:
  host: localhost
  queue: nutritionEventsQueue
caloriescalculator:
  weightFactor: 9.99
  heightFactor: 6.25
  ageFactor: -4.92
  deduction: -161
management:
  endpoints.web.exposure.include: health,info,refresh
